-- MySQL Script generated by MySQL Workbench
-- Thu Mar 21 18:44:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema organisme_formation
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema organisme_formation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `organisme_formation` DEFAULT CHARACTER SET utf8 ;
USE `organisme_formation` ;

-- -----------------------------------------------------
-- Table `organisme_formation`.`entreprises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `organisme_formation`.`entreprises` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `organisme_formation`.`salaries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `organisme_formation`.`salaries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `poste` VARCHAR(45) NOT NULL,
  `entreprises_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_salaries_entreprises1_idx` (`entreprises_id` ASC) ,
  CONSTRAINT `fk_salaries_entreprises1`
    FOREIGN KEY (`entreprises_id`)
    REFERENCES `organisme_formation`.`entreprises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `organisme_formation`.`professeurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `organisme_formation`.`professeurs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `organisme_formation`.`salles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `organisme_formation`.`salles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `organisme_formation`.`formations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `organisme_formation`.`formations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `dateDebut` DATETIME NOT NULL,
  `dateFin` DATETIME NOT NULL,
  `professeurs_id` INT NOT NULL,
  `coût` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_formations_professeurs1_idx` (`professeurs_id` ASC) ,
  CONSTRAINT `fk_formations_professeurs1`
    FOREIGN KEY (`professeurs_id`)
    REFERENCES `organisme_formation`.`professeurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `organisme_formation`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `organisme_formation`.`sessions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dateDebut` DATETIME NOT NULL,
  `dateFin` DATETIME NOT NULL,
  `professeurs_id` INT NOT NULL,
  `salles_id` INT NOT NULL,
  `formations_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sessions_professeurs1_idx` (`professeurs_id` ASC) ,
  INDEX `fk_sessions_salles1_idx` (`salles_id` ASC) ,
  INDEX `fk_sessions_formations1_idx` (`formations_id` ASC) ,
  CONSTRAINT `fk_sessions_professeurs1`
    FOREIGN KEY (`professeurs_id`)
    REFERENCES `organisme_formation`.`professeurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sessions_salles1`
    FOREIGN KEY (`salles_id`)
    REFERENCES `organisme_formation`.`salles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sessions_formations1`
    FOREIGN KEY (`formations_id`)
    REFERENCES `organisme_formation`.`formations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `organisme_formation`.`compte_rendus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `organisme_formation`.`compte_rendus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `professeurs_id` INT NOT NULL,
  `sessions_id` INT NOT NULL,
  `commentaire` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_compte_rendus_professeurs1_idx` (`professeurs_id` ASC) ,
  INDEX `fk_compte_rendus_sessions1_idx` (`sessions_id` ASC) ,
  CONSTRAINT `fk_compte_rendus_professeurs1`
    FOREIGN KEY (`professeurs_id`)
    REFERENCES `organisme_formation`.`professeurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compte_rendus_sessions1`
    FOREIGN KEY (`sessions_id`)
    REFERENCES `organisme_formation`.`sessions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `organisme_formation`.`notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `organisme_formation`.`notes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `note` FLOAT NULL,
  `salaries_id` INT NOT NULL,
  `formations_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notes_formations1_idx` (`formations_id` ASC) ,
  INDEX `fk_notes_salaries1_idx` (`salaries_id` ASC) ,
  CONSTRAINT `fk_notes_formations1`
    FOREIGN KEY (`formations_id`)
    REFERENCES `organisme_formation`.`formations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notes_salaries1`
    FOREIGN KEY (`salaries_id`)
    REFERENCES `organisme_formation`.`salaries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
