Professeur:
    type: entity
    table: professeurs
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        prenom:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
    lifecycleCallbacks: {  }
